### ISSUE TITLE
Calculation of percentage is wrong

### ISSUE THREAD

**Issue by Messinger** [DavideTriso/aria-progressbar#1]
https://github.com/DavideTriso/aria-progressbar/blob/27e90c49f9c02b5f0349b82e918a726613b00d33/src/js/aria-progressbar.js#L110

The line should be:

```javascript
self.valuePercent = (value*100.0)/(settings.maxVal - settings.minVal);
```

With your version it just works when max == 100

**Comment by DavideTriso** [comment]
Tank you for reporting. Fixed in v0.4.0. Also removed minVal option because unneeded.
